"""add upload settings

Revision ID: 2e0f21450f2f
Revises: 
Create Date: 2026-06-26 15:33:14.636665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0f21450f2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 執行升級前，先清空不重要的舊有暫存資料，避免 SQLite NOT NULL 衝突
    op.execute('DELETE FROM upload_sessions')
    op.add_column('upload_sessions', sa.Column('upload_token', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_sessions', 'upload_token')
    # ### end Alembic commands ###
